# Generated by Django 3.2.11 on 2022-05-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BinOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.PositiveIntegerField()),
                ('last_collection', models.DateTimeField(editable=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_ops.bin')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_ops.operation')),
            ],
        ),
    ]
